abstract: Driver-based API for sending SMS messages
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
build_requires: 
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: SMS-Send
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::Adapter: 1.00
  Module::Pluggable: 2.5
  Params::Util: 0.14
  perl: 5.005
version: 0.04
