---
abstract: 'Driver-based API for sending SMS messages'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: SMS::Send
name: SMS-Send
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Adapter: 1.05
  Class::Adapter::Builder: 1.05
  Module::Pluggable: 3.7
  Params::Util: 1.00
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/SMS-Send
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/SMS-Send
version: 1.06
