
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.03
name: SMS-Send
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  Module::Pluggable: 2.5
  perl: 5.005
  Params::Util: 0.14
  Class::Adapter: 1.00
  Carp: 0
abstract: Driver-based API for sending SMS messages
