name: SMS-Send
version: 0.02
abstract: Driver-based API for sending SMS messages
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
requires:
  perl: 5.005
  Carp: 0
  Params::Util: 0.02
  Class::Adapter: 1.00
  Module::Pluggable: 2.5
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.45
